# Generated by Django 3.0.6 on 2020-05-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='Img',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='Post_id',
        ),
        migrations.AddField(
            model_name='posts',
            name='Image',
            field=models.ImageField(default='images/None/no-image.jpg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='posts',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comments',
            name='Post_id',
            field=models.IntegerField(),
        ),
    ]
