# Generated by Django 3.0.6 on 2020-05-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200505_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='Likes',
            field=models.TextField(default="'[]'", max_length=10000),
        ),
        migrations.AlterField(
            model_name='users',
            name='Bookmarks',
            field=models.TextField(default="'[]'", max_length=10000),
        ),
    ]
