# Generated by Django 3.0.6 on 2020-05-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='Post_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notifications',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
