# Generated by Django 3.0.6 on 2020-05-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200511_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='Dp',
            field=models.ImageField(default='home/static/home/dp.jpg', upload_to='images'),
        ),
    ]
