# Generated by Django 3.0.6 on 2020-05-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_users_dp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Dp',
            field=models.ImageField(default='images/dp.jpg', upload_to='images'),
        ),
    ]
