# Generated by Django 3.0.6 on 2020-05-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200512_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Dp',
            field=models.ImageField(default='images/dp.jpg', upload_to='images/'),
        ),
    ]
