# Generated by Django 3.0.6 on 2020-05-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20200512_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='About',
            field=models.TextField(default='', max_length=10000),
        ),
    ]
