# Generated by Django 3.0.6 on 2020-06-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_users_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
